import { expandDataFields } from '../core/expandFields.js';
import type { CustomDictionaryEntry, EntitySchema, FieldSpec } from '../core/types.js';

/** `blogpost` -> `Blogpost`, `blog-post`/`blog_post` -> `BlogPost`: a TS-safe interface name for an entity. */
function pascalCase(entityName: string): string {
  return entityName
    .split(/[-_]/)
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

/** A JS identifier-safe field name is emitted bare; anything else (e.g. `"first-name"`) is quoted. */
function propertyKey(fieldName: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(fieldName) ? fieldName : JSON.stringify(fieldName);
}

/** All-primitive custom dictionaries become a literal union (`'ADMIN' | 'USER'`); anything else falls back to `string`. */
function customDictionaryType(entries: readonly CustomDictionaryEntry[] | undefined): string {
  if (!entries || entries.length === 0) return 'string';
  const literals = entries.map((entry) => entry.value);
  if (literals.every((v) => typeof v === 'string' || typeof v === 'number')) {
    return [...new Set(literals.map((v) => JSON.stringify(v)))].join(' | ');
  }
  return 'string';
}

/**
 * Maps one {@link FieldSpec} to a TS type string. `schemas`/`customDictionaries`
 * let `crossRef`/`custom` fields resolve to a real named type instead of a
 * generic fallback; `visiting` guards against a field-level cross-reference
 * cycle (rejected by `doctor` normally, but `types-gen` shouldn't hang/crash
 * if it's ever run standalone against an un-validated project).
 */
function fieldType(
  spec: FieldSpec,
  schemas: Record<string, EntitySchema>,
  customDictionaries: Record<string, readonly CustomDictionaryEntry[]> | undefined,
  visiting: Set<string>,
): string {
  switch (spec.kind) {
    case 'uuid':
    case 'username':
    case 'email':
    case 'hash':
    case 'lorem':
    case 'date':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'enumInline':
      return spec.values.map((v) => JSON.stringify(v)).join(' | ');
    case 'array':
      return `Array<${fieldType(spec.item, schemas, customDictionaries, visiting)}>`;
    case 'slugify':
      return 'string';
    case 'custom':
      return customDictionaryType(customDictionaries?.[spec.name]);
    case 'crossRef': {
      const targetSchema = schemas[spec.entity];
      if (spec.field === undefined) {
        // Bare relation: resolved at read time as the full
        // target entity's public shape, always an array.
        return targetSchema ? `${pascalCase(spec.entity)}[]` : 'unknown[]';
      }
      // Field-level relation: the stored value IS the target's field value.
      const targetField = targetSchema?.data[spec.field];
      const cycleKey = `${spec.entity}.${spec.field}`;
      if (!targetField || visiting.has(cycleKey)) return 'unknown';
      visiting.add(cycleKey);
      const resolved = fieldType(targetField, schemas, customDictionaries, visiting);
      visiting.delete(cycleKey);
      return resolved;
    }
  }
}

/**
 * Generates a single `.d.ts`-style source string with one `export interface`
 * per entity, so consuming code can write `fetch<User[]>('/api/user')`
 * without hand-duplicating the shape already described in `mock/api/**`.
 */
export function generateTypeDefinitions(
  schemas: Record<string, EntitySchema>,
  customDictionaries?: Record<string, readonly CustomDictionaryEntry[]>,
): string {
  const banner = [
    '// AUTO-GENERATED by `mpug types`. Do not edit by hand.',
    '// Regenerate with `npx mpug types` after changing mock/api/**.',
    '',
  ].join('\n');

  const interfaces = Object.values(schemas)
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((schema) => {
      const fields = expandDataFields(schema.data)
        .map(([fieldName, spec]) => `  ${propertyKey(fieldName)}: ${fieldType(spec, schemas, customDictionaries, new Set())};`)
        .join('\n');
      return `export interface ${pascalCase(schema.name)} {\n${fields}\n}`;
    })
    .join('\n\n');

  return `${banner}\n${interfaces}\n`;
}
