import { watch } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { loadConfig } from '../mockConfig.js';
import { loadProject } from '../schemaLoader.js';
import { asCommandFailure, ok, type CommandResult } from '../commandResult.js';

const GENERATED_DIR = '.generated';

const BANNER = [
  '// AUTO-GENERATED by `mpug codegen`. Do not edit by hand.',
  '// Regenerate with `npx mpug codegen` after changing mock/tables, routes or data.',
  '',
].join('\n');

/**
 * Emits a single importable module with the already-parsed schemas, routes,
 * dictionaries and config — the same thing `mockingpug/vite`'s virtual module
 * gives a Vite app, but as a real file for bundlers without a plugin (Metro /
 * React Native, Expo). Consume it with a plain `import`.
 */
function renderModule(project: Awaited<ReturnType<typeof loadProject>>, config: unknown): string {
  return [
    BANNER,
    "import type { EntitySchema, Route, CustomDictionaryEntry } from 'mockingpug';",
    '',
    `export const schemas: Record<string, EntitySchema> = ${JSON.stringify(project.entities, null, 2)};`,
    `export const routes: Route[] = ${JSON.stringify(project.routes, null, 2)};`,
    `export const customDictionaries: Record<string, CustomDictionaryEntry[]> = ${JSON.stringify(project.customDictionaries, null, 2)};`,
    `export const mockConfig = ${JSON.stringify(config, null, 2)} as const;`,
    '',
  ].join('\n');
}

async function generateOnce(projectDir: string): Promise<{ outPath: string; entities: number; routes: number }> {
  const config = await loadConfig(projectDir);
  const project = await loadProject(projectDir, config.dir);
  const outPath = join(projectDir, config.dir, GENERATED_DIR, 'schemas.ts');
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, renderModule(project, config), 'utf-8');
  return { outPath, entities: Object.keys(project.entities).length, routes: project.routes.length };
}

export interface CodegenOptions {
  /** Regenerate on every change under the mock dir (`--watch`). */
  watch?: boolean;
}

export async function codegen(projectDir: string, options: CodegenOptions = {}): Promise<CommandResult> {
  let first;
  try {
    first = await generateOnce(projectDir);
  } catch (error) {
    return asCommandFailure(error);
  }
  const relOut = relative(projectDir, first.outPath);
  const summary = [`wrote ${relOut}`, `${first.entities} tables, ${first.routes} routes`];
  if (!options.watch) return ok(summary);

  /* v8 ignore start -- long-lived watch loop, exercised manually */
  const config = await loadConfig(projectDir);
  const watchDir = join(projectDir, config.dir);
  console.log(`[mockingpug] ${summary.join(' — ')}; watching for changes (Ctrl-C to stop)…`);
  const watcher = watch(watchDir, { recursive: true }, (_event, filename) => {
    // Skip our own output, or writing it would re-trigger the watcher forever.
    if (filename && String(filename).split(/[/\\]/)[0] === GENERATED_DIR) return;
    generateOnce(projectDir)
      .then((r) => console.log(`[mockingpug] regenerated ${relative(projectDir, r.outPath)}`))
      .catch((error) => console.warn(`[mockingpug] codegen: ${(error as Error).message}`));
  });
  await new Promise(() => {}); // run until interrupted
  watcher.close();
  return ok(summary);
  /* v8 ignore stop */
}
